name: lifeline_iot
description: Intelligent Safety Beyond Networks - IoT Emergency Response System
publish_to: 'none'
version: 2.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Material Design
  cupertino_icons: ^1.0.6
  
  # State Management
  provider: ^6.1.1
  
  # IoT & Sensors
  sensors_plus: ^4.0.2
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  
  # Network & Communication
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  
  # QR Code
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  
  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  # Fonts
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700

  # Assets
  assets:
    - assets/images/
    - assets/icons/